baseURL: https://vandijke.xyz
languageCode: en-us
theme: "PaperMod"
title: vandijke.xyz
enableRobotsTXT: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Blog
          url: tags/blog
          weight: 5
        - name: About me
          url: about/
          weight: 10
 

params:
  env: production
  title: vandijke.xyz
  description: "Landing page of Martyn van Dijke"
  keywords: [Blog, Portfolio, PaperMod]
  author: Martyn van Dijke
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true

  assets:
    favicon: "/favicon.png"
    favicon16x16: "/favicon.png"
    favicon32x32: "/favicon.png"
    apple_touch_icon: "/favicon.png"
    safari_pinned_tab: "/favicon.png"

  label:
    text: "Home"
    icon: /favicon.png
    iconHeight: 35


  profileMode:
      enabled: true
      title: "Enthusiast selfhoster by night, DevOps engineer at day."
      subtitle: "Homepage of Martyn van Dijke"
      imageUrl: "/favicon.png"
      imageTitle: "logo"
      imageWidth: 120
      imageHeight: 120
      buttons:
        - name: projects & blog
          url: "https://vandijke.xyz/tags/blog/"

  socialIcons:
      - name: "github"
        url: "https://github.com/martynvdijke"
      - name: "instagram"
        url: "https://instagram.com/martynvandijke"
      - name: "linkedin"
        ulr: "https://linkedin.com/in/martynvandijke"

  outputs:
      home:
          - HTML
          - RSS
          - JSON
menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10